include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    todo: ignore

linter:
  rules:
    avoid_shadowing_type_parameters: false
    await_only_futures: true
    avoid_empty_else: false
