name: global
environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  effective_dart: ^1.1.1
  pedantic: ^1.8.0+1
  meta: ^1.8.0
  lint: ^2.1.0
  lints: ^4.0.0
  flutter_lints: ^4.0.0
  very_good_analysis: ^5.1.0
